MVC_Demo01/ViewModels/EditMemberDataView.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Job_Demo.ViewModel
{
    public class EditMemberDataView
    {

        [DisplayName("會員編號")]
        public string Id { get; set; }


        [DisplayName("姓名")]
        [Required(ErrorMessage = "請輸入姓名")]
        public string UserName { get; set; }


        [DisplayName("電子郵件")]
        public string Email { get; private set; }


        [DisplayName("生日")]

        public string Birthday { get; set; }

        [DisplayName("手機號碼")]
        public string PhoneNember { get; set; }

        [DisplayName("地址")]
        public string Address { get; set; }

    }
}

MVC_Demo01/Controllers/MyAccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Job_Demo.Models;
using Job_Demo.ViewModel;
using Job_Demo.Services;
using System.Web.Security;

namespace Job_Demo.Controllers
{
    public class MyAccountController : Controller
    {
        public Job_DemoDBEntities db = new Job_DemoDBEntities();
        public EditMemberDataService editMemberDataService = new EditMemberDataService();
        // GET: MyAccount
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult EditMemberData()
        {

            var cookies = Request.Cookies[FormsAuthentication.FormsCookieName];
            var tickets = FormsAuthentication.Decrypt(cookies.Value);
            string role = tickets.UserData;
            var result = (from x in db.Account where x.Email == role select x).ToList();
            Account Data = editMemberDataService.GetDataByEmail(role);

            return View(Data);

        }

        [HttpPost]
        public ActionResult EditMemberData(Account MemberData)
        {
            var cookies = Request.Cookies[FormsAuthentication.FormsCookieName];
            var tickets = FormsAuthentication.Decrypt(cookies.Value);
            string role = tickets.UserData;
            if (editMemberDataService.CheckUpdate(role))
            {
                editMemberDataService.UpdateAccount(MemberData);
                TempData["UpdateDataResult"] = "修改成功";
                return RedirectToAction("UpdateMemberDataResult");
            }
            return RedirectToAction("Index", "HotSpot");
        }

        public ActionResult UpdateMemberDataResult()
        {
            return View();
        }
    }
}

MVC_Demo01/Views/MyAccount/EditMemberData.cshtml
@model Job_Demo.Models.Account

@{
    ViewBag.Title = "EditMemberData";
}

<h2>修改會員資料</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)


        <div class="form-group">
            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" , disabled = "disabled" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="修改資料" class="btn btn-default" />
            </div>
        </div>
    </div>
}
<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

MVC_Demo01/Views/MyAccount/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>會員中心</h2>

@Html.ActionLink("修改密碼", "ChangePassword", "Portal")
@Html.ActionLink("修改會員資料", "EditMemberData", "MyAccount")

MVC_Demo01/Views/MyAccount/UpdateMemberDataResult.cshtml
@{
    ViewBag.Title = "UpdateMemberDataResult";
}

<h2>修改成功</h2>
<div>
    @TempData["UpdateDataResult"]
</div>
<div>
    @Html.ActionLink("回首頁", "Index", "HotSpot")
</div>